/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_husker_openglfx_utils_NativeWindowUtils */

#ifndef _Included_com_husker_openglfx_utils_NativeWindowUtils
#define _Included_com_husker_openglfx_utils_NativeWindowUtils
#ifdef __cplusplus
extern "C" {
#endif
    /*
     * Class:     com_husker_openglfx_utils_NativeWindowUtils
     * Method:    hideWindowWin32
     * Signature: (J)V
     */
JNIEXPORT void JNICALL Java_com_husker_openglfx_utils_NativeWindowUtils_hideWindowWin32
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
