name: Maven Central publishing

on:
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: "Importing GPG key"
        run: |
          sudo gpg --batch --passphrase ${{ secrets.GPG_PASSPHRASE }} --import gradle/secring.gpg

      - name: "Install build dependencies"
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install g++-multilib

      - name: "Prepare"
        run: |
          chmod +x ./gradlew

      - name: "Building and publishing"
        run: >
          ./gradlew publish
          -Dorg.gradle.jvmargs=-Xmx4096M
          -Dorg.gradle.project.signing.password=${{ secrets.GPG_PASSPHRASE }}
          -Dorg.gradle.project.signing.secretKeyRingFile=${{ github.workspace }}/gradle/secring.gpg
          -Dorg.gradle.project.ossrhUsername=${{ secrets.SONATYPE_USERNAME }}
          -Dorg.gradle.project.ossrhPassword=${{ secrets.SONATYPE_PASSWORD }}

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: "Importing GPG key"
        run: |
          gpg --batch --passphrase ${{ secrets.GPG_PASSPHRASE }} --import gradle/secring.gpg

      - name: "Building and publishing"
        run: >
          ./gradlew publishNatives
          "-Dorg.gradle.project.signing.password=${{ secrets.GPG_PASSPHRASE }}"
          "-Dorg.gradle.project.signing.secretKeyRingFile=${{ github.workspace }}/gradle/secring.gpg"
          "-Dorg.gradle.project.ossrhUsername=${{ secrets.SONATYPE_USERNAME }}"
          "-Dorg.gradle.project.ossrhPassword=${{ secrets.SONATYPE_PASSWORD }}"

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Importing GPG key"
        run: |
          gpg --batch --passphrase ${{ secrets.GPG_PASSPHRASE }} --import gradle/secring.gpg

      - name: "Prepare"
        run: |
          chmod +x ./gradlew

      - name: "Building and publishing"
        run: >
          ./gradlew publishNatives
          -Dorg.gradle.project.signing.password=${{ secrets.GPG_PASSPHRASE }}
          -Dorg.gradle.project.signing.secretKeyRingFile=${{ github.workspace }}/gradle/secring.gpg
          -Dorg.gradle.project.ossrhUsername=${{ secrets.SONATYPE_USERNAME }}
          -Dorg.gradle.project.ossrhPassword=${{ secrets.SONATYPE_PASSWORD }}
